apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
        - name: transmission
          image: lscr.io/linuxserver/transmission:latest
          ports:
            - containerPort: 9091
            - containerPort: 51413
            - containerPort: 51413
              protocol: UDP
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Rome
            - name: TRANSMISSION_DOWNLOAD_DIR
              value: /data
            - name: TRANSMISSION_INCOMPLETE_DIR
              value: /data/.incomplete
            - name: TRANSMISSION_WATCH_DIR
              value: /data/.watch
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: transmission-config
        - name: data
          persistentVolumeClaim:
            claimName: media-data
---
apiVersion: v1
kind: Service
metadata:
  name: transmission
  namespace: media
spec:
  selector:
    app: transmission
  ports:
    - name: web
      port: 9091
      targetPort: 9091
    - name: torrent-tcp
      port: 51413
      targetPort: 51413
    - name: torrent-udp
      port: 51413
      targetPort: 51413
      protocol: UDP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transmission
  namespace: media
  annotations:
    ingress.cilium.io/force-https: "disabled"
spec:
  ingressClassName: cilium
  tls:
    - hosts:
        - transmission.patat.in
      secretName: wildcard-patat-in-tls
  rules:
    - host: transmission.patat.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: transmission
                port:
                  number: 9091
