apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-patat-in
  namespace: cert-manager
spec:
  secretName: wildcard-patat-in-tls
  dnsNames:
    - patat.in
    - '*.patat.in'
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "argocd,dashy,media,homeassistant,esphome"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
