all:
  hosts:
    pi-alpha.lan:
      ansible_host: 192.168.8.11
      ansible_user: root
    pi-beta.lan:
      ansible_host: 192.168.8.12
      ansible_user: root
    pi-delta.lan:
      ansible_host: 192.168.8.13
      ansible_user: root
    pi-epsilon.lan:
      ansible_host: 192.168.8.14
      ansible_user: root
    pi-gamma.lan:
      ansible_host: 192.168.8.15
      ansible_user: root
  children:
    cluster:
      hosts:
        # pi-alpha.lan:
        # pi-beta.lan:
        pi-gamma.lan:
        pi-delta.lan:
        pi-epsilon.lan:
    controllers:
      hosts:
        pi-delta.lan:
        pi-epsilon.lan:
        pi-gamma.lan:

