apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snips
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/di3go-sona/homelab.git
    targetRevision: main
    path: src/argo/apps/snips/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: snips
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
