# - name: Update OS and install base services
#   ansible.builtin.import_playbook: playbooks/base.yml

- name: Configure and mount SMB share
  ansible.builtin.import_playbook: playbooks/storage.yml

- name: Deploy monitoring stack
  ansible.builtin.import_playbook: playbooks/monitoring.yml
  