apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argo-helm.git
    targetRevision: argo-cd-6.7.11
    path: charts/argo-cd
    helm:
      values: |
        configs:
          cm:
            users.anonymous.enabled: "true"
          rbac:
            policy.default: "role:admin"
        server:
          extraArgs:
            - --insecure
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
