# Stop and remove all containers 
- name: Stop all containers
  become: yes
  ansible.builtin.shell: |
    docker ps -q | xargs -r docker stop
  ignore_errors: yes

# System prune docker
- name: Prune Docker system
  become: yes
  ansible.builtin.shell: |
    docker system prune -af
  ignore_errors: yes

# Remove the homelab directory
- name: Remove homelab directory
  become: yes
  ansible.builtin.file:
    path: "{{ homelab_root_dir }}"
    state: absent