---
- name: Check if Cilium is already installed
  command:
    cmd: helm status cilium --namespace kube-system --kubeconfig {{ k0s_kubeconfig_file }}
  register: argocd_cilium_check
  failed_when: false
  changed_when: false

- name: Add Cilium Helm repo
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/
  when: argocd_cilium_check.rc != 0

- name: Install Cilium
  command:
    cmd: >
      helm upgrade --install cilium cilium/cilium
      --version 1.15.5
      --namespace kube-system
      --create-namespace
      --kubeconfig {{ k0s_kubeconfig_file }}
      --set kubeProxyReplacement=true
      --set k8sServiceHost={{ hostvars[groups['cluster'][0]]['ansible_host'] }}
      --set k8sServicePort=6443
  changed_when: true
  when: argocd_cilium_check.rc != 0

- name: Check if ArgoCD is already installed
  command:
    cmd: helm status argocd --namespace argocd --kubeconfig {{ k0s_kubeconfig_file }}
  register: argocd_self_check
  failed_when: false
  changed_when: false

- name: Add ArgoCD Helm repo
  kubernetes.core.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm
  when: argocd_self_check.rc != 0

- name: Install ArgoCD
  command:
    cmd: >
      helm upgrade --install argocd argo/argo-cd
      --version 6.7.11
      --namespace argocd
      --create-namespace
      --kubeconfig {{ k0s_kubeconfig_file }}
      --set configs.cm."users\.anonymous\.enabled"=true
      --set configs.rbac."policy\.default"=role:admin
  changed_when: true
  when: argocd_self_check.rc != 0

- name: Wait for ArgoCD server to be ready
  command:
    cmd: kubectl --kubeconfig {{ k0s_kubeconfig_file }} rollout status deployment/argocd-server -n argocd --timeout=120s
  changed_when: false

- name: Bootstrap app-of-apps
  command:
    cmd: kubectl --kubeconfig {{ k0s_kubeconfig_file }} apply -f {{ playbook_dir }}/../../src/argo/app-of-apps.yaml
  changed_when: true
