{
 "title": "Nodes Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "label": "Hostname", "query": { "query": "label_values(up,instance)" } },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(container_cpu_load_average_10s,name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "host" },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',instance=~\"^$host:.*\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"^$host:.*\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"^$host:.*\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"^$host:.*\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',instance=~\"^$host:.*\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy User"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"^$host:.*\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"^$host:.*\"} - node_memory_MemFree_bytes{instance=~\"^$host:.*\"} - (node_memory_Cached_bytes{instance=~\"^$host:.*\"} + node_memory_Buffers_bytes{instance=~\"^$host:.*\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"^$host:.*\"} + node_memory_Buffers_bytes{instance=~\"^$host:.*\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"^$host:.*\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"^$host:.*\"} - node_memory_SwapFree_bytes{instance=~\"^$host:.*\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (device, fstype, mountpoint) (node_filesystem_avail_bytes{instance=~\"^$host:.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (device, fstype, mountpoint) ((node_filesystem_size_bytes{instance=~\"^$host:.*\"}-node_filesystem_avail_bytes{instance=~\"^$host:.*\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Services",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "sum by (id, name) (irate(container_cpu_usage_seconds_total{instance=~\"^$host:.*\",name=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum by (id, name) (irate(container_memory_rss{instance=~\"^$host:.*\",name=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}