services:
  prometheus:
    build: .
    ports:
      - "9090:9090"
    volumes:
      - /opt/homelab/prometheus/etc:/etc/prometheus
      - /opt/homelab/prometheus/var/lib:/var/lib/prometheus
    command:
      - 'prometheus'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/var/lib/prometheus'