router:
  hosts:
    router.lan:

cluster:
  hosts:
    pi-alpha.lan:
      ansible_user: di3go-sona
    pi-beta.lan:
      ansible_user: di3go-sona
    pi-gamma.lan:
      ansible_user: di3go-sona

monitoring:
  hosts:
    pi-beta.lan:
      ansible_user: di3go-sona

storage:
  hosts:
    pi-alpha.lan:
      ansible_user: di3go-sona

services:
  hosts:
    pi-gamma.lan:
      ansible_user: di3go-sona