- name: Create directories and copy files for homeassistant
  ansible.builtin.include_role: 
    name: utils
    tasks_from: tree.yml
  vars:
    item: homeassistant

- name: Build and run docker compose for homeassistant
  ansible.builtin.include_role: 
    name: utils
    tasks_from: docker.yml
  vars:
    item: homeassistant