
- name: Ensure k0sctl is installed
  command: k0sctl version
  register: k0sctl_check
  changed_when: false

- name: Fail if k0sctl is not installed
  fail:
    msg: "k0sctl is not installed on localhost. Please install it first."
  when: k0sctl_check.rc != 0

- name: Render k0sctl config
  template:
    src: k0sctl.yaml.j2
    dest: "{{ playbook_dir }}/k0sctl.yaml"
    mode: '0644'

- name: Reset k0s cluster
  command: k0sctl reset --config "{{ playbook_dir }}/k0sctl.yaml" --force
  when: k0s_recreate | default(false) | bool
  delegate_to: localhost
  run_once: true

# - name: Apply k0s cluster configuration
#   command: k0sctl apply --config "{{ playbook_dir }}/k0sctl.yaml"
#   delegate_to: localhost
#   run_once: true

- name: Get kubeconfig
  command: k0sctl kubeconfig --config "{{ playbook_dir }}/k0sctl.yaml"
  register: k0s_kubeconfig
  changed_when: false
  delegate_to: localhost
  run_once: true

- name: Create .kube directory if it doesn't exist
  file:
    dest: "~/.kube"
    state: directory
    mode: '0700'
  delegate_to: localhost
  run_once: true

- name: Write kubeconfig to file
  copy:
    content: "{{ k0s_kubeconfig.stdout }}"
    dest: "~/.kube/config.homelab"
    mode: '0600'
  delegate_to: localhost
  run_once: true

- name: Add kubeconfig to zshrc
  lineinfile:
    path: "~/.zshrc"
    line: 'export KUBECONFIG=$KUBECONFIG:$HOME/.kube/config.homelab'
    state: present
    create: true
  delegate_to: localhost
  run_once: true



