- name: Create directories and copy files for prometheus_blackbox_exporter
  ansible.builtin.include_role: 
    name: utils
    tasks_from: tree.yml
  vars:
    item: prometheus_blackbox_exporter

- name: Build and run docker compose for prometheus_blackbox_exporter
  ansible.builtin.include_role: 
    name: utils
    tasks_from: docker.yml
  vars:
    item: prometheus_blackbox_exporter