- name: Basic setup for all servers
  hosts: all
  roles:
    - role: base
    - role: mounts

- name: Setup kubernetes cluster
  hosts: localhost
  roles:
    - role: k0s
    - role: helm
      tags: helm
      
