- name: Basic setup for all servers
  hosts: all
  roles:
    - role: os
      tags: os
    - role: storage
      tags: storage
    - role: netbird
      tags: netbird

- name: Setup kubernetes cluster
  hosts: localhost
  roles:
    - role: k0s
      tags: k0s
    - role: helm
      tags: helm
