router:
  hosts:
    router.lan:

k3s_cluster:
  hosts:
    pi-alpha.lan:
      ansible_host: 192.168.8.11
      ansible_user: root
    pi-beta.lan:
      ansible_host: 192.168.8.12
      ansible_user: root
    pi-gamma.lan:
      ansible_host: 192.168.8.13
      ansible_user: root
    pi-delta.lan:
      ansible_host: 192.168.8.14
      ansible_user: root
    pi-epsilon.lan:
      ansible_host: 192.168.8.15
      ansible_user: root
  children:
    agent:
      pi-alpha.lan:
      pi-beta.lan:
    server:
      pi-gamma.lan:
      pi-delta.lan:
      pi-epsilon.lan:





  # Required Vars
  vars:
    ansible_port: 22
    ansible_user: debian
    k3s_version: v1.34.2+k3s1
    # The token should be a random string of reasonable length. You can generate
    # one with the following commands:
    # - openssl rand -base64 64
    # - pwgen -s 64 1
    # You can use ansible-vault to encrypt this value / keep it secret.
    # Or you can omit it if not using Vagrant and let the first server automatically generate one.
    token: "ZlEj9Kg+cpVYMbU3FrhwQEjGrA7yugTMzHX5MnXXsBfCuIX32culZRypRAnX0+rZdZh0GeZTJd270NPFrUXZ+Q=="
    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"